service: salesforce-finance-contact-sync

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-cloud-elements-plugin

functions:
  sync:
    handler: contactSync.eventHandler
    timeout: 30
    memorySize: 256
    events:
      - instance:
          resource: source

resources:
  Resources:
    source:
      Type: CE::Element::sfdc
      Properties:
        id: ${env:SOURCE_ID}
    dest:
      Type: CE::Hub::general
      Properties:
        id: ${env:DEST_ID}
    account:
      Type: CE::Account
      Properties:
        userToken: ${env:USER_TOKEN}
        orgToken: ${env:ORG_TOKEN}
        baseUrl: ${env:BASE_URL}
